name: Experiment
on: 
  pull_request:

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: debug }
    - name: Add files
      run: echo "hello world" > trufflehog-anzx-debug.out
    - name: Commit back to GitHub
      run: |
        git add -A
        git commit -m "Updating some file"
        git push

